//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docentliksitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class İcerikler
    {
        public int id { get; set; }
        public string icerikadi { get; set; }
        public Nullable<int> puan { get; set; }
        public Nullable<int> konuid { get; set; }
        public Nullable<int> alanid { get; set; }
    
        public virtual Konular Konular { get; set; }
    }
}
