//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docentliksitesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tezEntities2 : DbContext
    {
        public tezEntities2()
            : base("name=tezEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<Alanlar> Alanlar { get; set; }
        public virtual DbSet<Haberler> Haberler { get; set; }
        public virtual DbSet<İcerikler> İcerikler { get; set; }
        public virtual DbSet<Konular> Konular { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
